const simActionTypes = {
    SIM_CHECK_SUCCESS: 'SIM_CHECK_SUCCESS',
    SIM_CHECK_FAILURE: 'SIM_CHECK_FAILURE',
    SIM_ACTIVATION_SUCCESS: 'SIM_ACTIVATION_SUCCESS',
    SIM_ACTIVATION_FAILURE: 'SIM_ACTIVATION_FAILURE',
    SIM_CLEAR_REQUEST: 'SIM_CLEAR_REQUEST',
}

export default simActionTypes;