const toasterActionTypes = {
    TOASTER_SHOW_ERROR_MESSAGE: 'TOASTER_SHOW_ERROR_MESSAGE',
    TOASTER_SHOW_SUCCESS_MESSAGE: 'TOASTER_SHOW_SUCCESS_MESSAGE',
    TOASTER_SHOW_WARNING_MESSAGE: 'TOASTER_SHOW_WARNING_MESSAGE',
    TOASTER_SHOW_INFO_MESSAGE: 'TOASTER_SHOW_INFO_MESSAGE',
    TOASTER_HIDE_MESSAGE: 'TOASTER_HIDE_MESSAGE',
}

export default toasterActionTypes;