const userActionTypes = {
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    USERS_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    USERS_LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',
}

export default userActionTypes;